/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Cashfree.PG.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;


public class OrderPayResponse {
    /**
     * API related Errors
     */
    
    public Cashfree.PG.models.shared.ApiError apiError;

    public OrderPayResponse withApiError(Cashfree.PG.models.shared.ApiError apiError) {
        this.apiError = apiError;
        return this;
    }
    
    
    public String contentType;

    public OrderPayResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    /**
     * Any bad or invalid request will lead to following error object
     */
    
    public Cashfree.PG.models.shared.ErrorResponse errorResponse;

    public OrderPayResponse withErrorResponse(Cashfree.PG.models.shared.ErrorResponse errorResponse) {
        this.errorResponse = errorResponse;
        return this;
    }
    
    
    public java.util.Map<String, String[]> headers;

    public OrderPayResponse withHeaders(java.util.Map<String, String[]> headers) {
        this.headers = headers;
        return this;
    }
    
    /**
     * OK
     */
    
    public Cashfree.PG.models.shared.OrderPayResponse orderPayResponse;

    public OrderPayResponse withOrderPayResponse(Cashfree.PG.models.shared.OrderPayResponse orderPayResponse) {
        this.orderPayResponse = orderPayResponse;
        return this;
    }
    
    /**
     * Either ports issue or too many requests
     */
    
    public Cashfree.PG.models.shared.RateLimitError rateLimitError;

    public OrderPayResponse withRateLimitError(Cashfree.PG.models.shared.RateLimitError rateLimitError) {
        this.rateLimitError = rateLimitError;
        return this;
    }
    
    
    public Integer statusCode;

    public OrderPayResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public OrderPayResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    public OrderPayResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
