/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Cashfree.PG.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * RateLimitErrorType - rate_limit_error
 */
public enum RateLimitErrorType {
    RATE_LIMIT_ERROR("rate_limit_error");

    @JsonValue
    public final String value;

    private RateLimitErrorType(String value) {
        this.value = value;
    }
}
